# Generated by Django 6.0 on 2026-01-26 20:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0003_alter_ordemservico_cliente'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordemservico',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.orcamento'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.veiculo'),
        ),
    ]
