# Generated by Django 6.0 on 2026-01-26 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('core', '0004_alter_ordemservico_orcamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_core', to='clientes.cliente'),
        ),
        migrations.RemoveField(
            model_name='veiculo',
            name='cliente',
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_core', to='clientes.veiculo'),
        ),
        migrations.RemoveField(
            model_name='ordemservico',
            name='data_abertura',
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='orcamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.orcamento'),
        ),
        migrations.AlterField(
            model_name='ordemservico',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordens_servico', to='clientes.veiculo'),
        ),
        migrations.AlterField(
            model_name='pecaos',
            name='peca',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.peca'),
        ),
        migrations.AlterField(
            model_name='pecaos',
            name='quantidade',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.DeleteModel(
            name='Veiculo',
        ),
    ]
