# Generated by Django 6.0 on 2026-01-27 11:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_ordemservico_data_fechamento_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('placa', models.CharField(max_length=10, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='movimentofinanceiro',
            name='categoria',
            field=models.CharField(choices=[('mao_obra', 'Mão de Obra'), ('peca', 'Peça'), ('compra_peca', 'Compra de Peça'), ('nf_emitida', 'Nota Fiscal Emitida'), ('nf_recebida', 'Nota Fiscal Recebida'), ('outros', 'Outros')], default='GERAL', max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentofinanceiro',
            name='criado_em',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='movimentofinanceiro',
            name='ordem_servico',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='movimentos_financeiros', to='core.ordemservico'),
        ),
        migrations.AlterField(
            model_name='movimentofinanceiro',
            name='descricao',
            field=models.CharField(max_length=255),
        ),
    ]
