# Generated by Django 6.0 on 2026-01-27 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_veiculo_movimentofinanceiro_categoria_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pecaos',
            name='peca',
        ),
        migrations.AddField(
            model_name='pecaos',
            name='nome',
            field=models.CharField(default=1, max_length=150),
            preserve_default=False,
        ),
    ]
