# Generated by Django 6.0 on 2026-01-26 20:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clientes', '0001_initial'),
        ('orcamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orcamento',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_app', to='clientes.cliente'),
        ),
        migrations.AlterField(
            model_name='orcamento',
            name='veiculo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orcamentos_app', to='clientes.veiculo'),
        ),
    ]
